name: glyphgit
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - vector
  - tasty
  - tasty-quickcheck
  - process

library:
  source-dirs: src

executables:
  fractal-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - glyphgit

tests:
  glyphgit-test:
    main: Stress7D.hs
    source-dirs: test
    dependencies:
      - glyphgit